### ISSUE TITLE
Fix Regex for Minified Styles

### ISSUE THREAD

**Issue by inbrighttech** [conall-hawks/css-vars#1]
Thank you for this, 

I suggest changing your Find CSS Variables regex from this

`/(--[^;)]+:.+;)/g;`

To this

`/(--([\w-]+)\s*:\s*([^;\}]+)\s*[;\^}])/g`

**Comment by inbrighttech** [comment]
this one is better

`/(--([\w-]+)\s*:\s*([^;\}]+)\s*[;]?)/g`

Does not include curly braces at the end.

**Comment by jon-hawks** [comment]
Thank you for this!

I've included it in a recent update. :)
